from __future__ import annotations

from app.configs.paths import ROOT


REQUIRED_ENV_KEYS = (
    "AUTORESEARCH_API_KEY",
    "AUTORESEARCH_API_BASE",
    "AUTORESEARCH_PRIMARY_MODEL",
    "AUTORESEARCH_TEMPERATURE",
    "AUTORESEARCH_MAX_TOKENS",
    "AUTORESEARCH_TIMEOUT_S",
)
AVAILABLE_MODELS_ENV_KEY = "AUTORESEARCH_AVAILABLE_MODELS"
LLM_CONCURRENCY_ENV_KEY = "AUTORESEARCH_LLM_CONCURRENCY"
DEFAULT_LLM_CONCURRENCY = 20

__all__ = [
    "AVAILABLE_MODELS_ENV_KEY",
    "DEFAULT_LLM_CONCURRENCY",
    "LLM_CONCURRENCY_ENV_KEY",
    "REQUIRED_ENV_KEYS",
    "ROOT",
]
